flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_booking_initializeApi_step["🌐 initialize"]:::apiStyle
    steps_booking_noop_userSendsMessage_step["⚙️ User Sends Message"]:::noopStyle
    steps_booking_searchCustomer_step["⚡ Search Customer"]:::eventStyle
    steps_booking_searchTicketUpgrades_step["⚡ Search Ticket Upgrades"]:::eventStyle
    steps_booking_searchUpgradesApi_step["🌐 DBZ Search Upgrades"]:::apiStyle
    steps_booking_sendText_step["⚡ Send SMS"]:::eventStyle
    steps_booking_initializeApi_step -->|dbz.search-customer| steps_booking_searchCustomer_step
    steps_booking_noop_userSendsMessage_step -->|/api/dbz/search-upgrades| steps_booking_searchUpgradesApi_step
    steps_booking_searchCustomer_step -->|dbz.send-text| steps_booking_sendText_step
    steps_booking_searchTicketUpgrades_step -->|dbz.send-text| steps_booking_sendText_step
    steps_booking_searchUpgradesApi_step -->|dbz.evaluate-upgrades| steps_booking_searchTicketUpgrades_step
    steps_booking_sendText_step -->|dbz.message-sent| steps_booking_noop_userSendsMessage_step
