flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_cronExample_handlePeriodicJob_step["⚡ HandlePeriodicJob"]:::eventStyle
    steps_cronExample_periodicJob_step["⏰ PeriodicJob"]:::cronStyle
    steps_cronExample_periodicJob_step -->|cron-ticked| steps_cronExample_handlePeriodicJob_step
