flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_endpointServerHandshake_apiCaller_step["⚡ API Caller"]:::eventStyle
    steps_endpointServerHandshake_handshakeApi_step["🌐 Endpoint Server Handshake"]:::apiStyle
    steps_endpointServerHandshake_nodeFinalizer_step["⚡ Node Finalizer"]:::eventStyle
    steps_endpointServerHandshake_nodeStarter_step["⚡ Node Starter"]:::eventStyle
    steps_endpointServerHandshake_apiCaller_step -->|handshake.apiResponse| steps_endpointServerHandshake_nodeFinalizer_step
    steps_endpointServerHandshake_handshakeApi_step -->|handshake.initiate| steps_endpointServerHandshake_nodeStarter_step
    steps_endpointServerHandshake_nodeStarter_step -->|handshake.callApi| steps_endpointServerHandshake_apiCaller_step
