flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_hybridEndpointExample_analyzeData_step_py["⚡ Analyze Data"]:::eventStyle
    steps_hybridEndpointExample_enrichData_step["⚡ Enrich Data"]:::eventStyle
    steps_hybridEndpointExample_finalizeData_step["⚡ Fanialize Data"]:::eventStyle
    steps_hybridEndpointExample_hybridApi_step["🌐 Hybrid Endpoint Example"]:::apiStyle
    steps_hybridEndpointExample_transformData_step_py["⚡ Transform Data"]:::eventStyle
    steps_hybridEndpointExample_analyzeData_step_py -->|hybrid.analyzed| steps_hybridEndpointExample_finalizeData_step
    steps_hybridEndpointExample_enrichData_step -->|hybrid.enriched| steps_hybridEndpointExample_analyzeData_step_py
    steps_hybridEndpointExample_hybridApi_step -->|hybrid.validated| steps_hybridEndpointExample_transformData_step_py
    steps_hybridEndpointExample_transformData_step_py -->|hybrid.transformed| steps_hybridEndpointExample_enrichData_step
