flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_wistroServerExample_finalizer_step["⚡ Finalizer"]:::eventStyle
    steps_wistroServerExample_processor_step["⚡ Processor"]:::eventStyle
    steps_wistroServerExample_startServerExample_step["🌐 Start Event"]:::apiStyle
    steps_wistroServerExample_processor_step -->|ws-server-example.processed| steps_wistroServerExample_finalizer_step
    steps_wistroServerExample_startServerExample_step -->|ws-server-example.start| steps_wistroServerExample_processor_step
