flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_openAi_callOpenAi_step["⚡ Call OpenAI"]:::eventStyle
    steps_openAi_callOpenAiApi_step_py["🌐 Call OpenAI"]:::apiStyle
    steps_openAi_callOpenAiApi_step_rb["🌐 Call OpenAI"]:::apiStyle
    steps_openAi_callOpenAiApi_step["🌐 Call OpenAI"]:::apiStyle
    steps_openAi_call_ai_step_py["⚡ Call OpenAI"]:::eventStyle
    steps_openAi_call_ai_ruby_step_rb["⚡ Call OpenAI"]:::eventStyle
    steps_openAi_openAiResponse_step["⚡ OpenAI Response"]:::eventStyle
    steps_openAi_callOpenAi_step -->|OpenAI Response| steps_openAi_openAiResponse_step
    steps_openAi_callOpenAiApi_step_py -->|call-openai| steps_openAi_callOpenAi_step
    steps_openAi_callOpenAiApi_step_py -->|call-openai| steps_openAi_call_ai_step_py
    steps_openAi_callOpenAiApi_step_py -->|call-openai| steps_openAi_call_ai_ruby_step_rb
    steps_openAi_callOpenAiApi_step_rb -->|call-openai| steps_openAi_callOpenAi_step
    steps_openAi_callOpenAiApi_step_rb -->|call-openai| steps_openAi_call_ai_step_py
    steps_openAi_callOpenAiApi_step_rb -->|call-openai| steps_openAi_call_ai_ruby_step_rb
    steps_openAi_callOpenAiApi_step -->|call-openai| steps_openAi_callOpenAi_step
    steps_openAi_callOpenAiApi_step -->|call-openai| steps_openAi_call_ai_step_py
    steps_openAi_callOpenAiApi_step -->|call-openai| steps_openAi_call_ai_ruby_step_rb
    steps_openAi_call_ai_step_py -->|openai-response| steps_openAi_openAiResponse_step
    steps_openAi_call_ai_ruby_step_rb -->|openai-response| steps_openAi_openAiResponse_step
