flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_parallelMergeState_joinComplete_step["⚡ Join Complete"]:::eventStyle
    steps_parallelMergeState_joinStep_step["⚡ join-step"]:::eventStyle
    steps_parallelMergeState_noopStartButton_step["⚙️ Test the flow"]:::noopStyle
    steps_parallelMergeState_startParallelMerge_step["🌐 Parallel Merge"]:::apiStyle
    steps_parallelMergeState_stepA_step["⚡ stepA"]:::eventStyle
    steps_parallelMergeState_stepB_step_py["⚡ stepB"]:::eventStyle
    steps_parallelMergeState_stepC_step_rb["⚡ stepC"]:::eventStyle
    steps_parallelMergeState_joinStep_step -->|pms.join.complete| steps_parallelMergeState_joinComplete_step
    steps_parallelMergeState_noopStartButton_step -->|/api/parallel-merge| steps_parallelMergeState_startParallelMerge_step
    steps_parallelMergeState_startParallelMerge_step -->|pms.start| steps_parallelMergeState_stepA_step
    steps_parallelMergeState_startParallelMerge_step -->|pms.start| steps_parallelMergeState_stepB_step_py
    steps_parallelMergeState_startParallelMerge_step -->|pms.start| steps_parallelMergeState_stepC_step_rb
    steps_parallelMergeState_stepA_step -->|pms.stepA.done| steps_parallelMergeState_joinStep_step
    steps_parallelMergeState_stepB_step_py -->|pms.stepB.done| steps_parallelMergeState_joinStep_step
    steps_parallelMergeState_stepC_step_rb -->|pms.stepC.done| steps_parallelMergeState_joinStep_step
