flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_testState_checkStateChange_step["⚡ Check state change"]:::eventStyle
    steps_testState_check_state_change_step_rb["⚡ Test State With Ruby"]:::eventStyle
    steps_testState_testState_api_step["🌐 Test state api trigger"]:::apiStyle
    steps_testState_test_state_step_py["⚡ Test State With Python"]:::eventStyle
    steps_testState_testState_api_step -->|test-state| steps_testState_test_state_step_py
    steps_testState_test_state_step_py -->|check-state-change| steps_testState_checkStateChange_step
    steps_testState_test_state_step_py -->|check-state-change| steps_testState_check_state_change_step_rb
