/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FlowIdImport } from './routes/flow/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FlowIdRoute = FlowIdImport.update({
  id: '/flow/$id',
  path: '/flow/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flow/$id': {
      id: '/flow/$id'
      path: '/flow/$id'
      fullPath: '/flow/$id'
      preLoaderRoute: typeof FlowIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow/$id': typeof FlowIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow/$id': typeof FlowIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flow/$id': typeof FlowIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flow/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flow/$id'
  id: '__root__' | '/' | '/flow/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowIdRoute: typeof FlowIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowIdRoute: FlowIdRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flow/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flow/$id": {
      "filePath": "flow/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
