name: Deploy motiaui to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy to Cloudflare Pages

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./dist
          branch: main

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker
        run: wrangler publish --api-token ${{ secrets.CF_API_TOKEN }}

# 如有 worker.js 或 wrangler.toml 具体路径或自定义需求请补充说明，本文件默认 worker.js 在 dist 目录下。
